name: Deploy with Compose

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Docker Login
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build & Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/backend-app:${{ github.sha }} -t ${{ secrets.DOCKERHUB_USERNAME }}/backend-app:latest .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend-app:${{ github.sha }}
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend-app:latest

    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd backend
          git pull origin main
          docker-compose down
          docker-compose pull
          docker-compose up -d

